FROM php:7.2-fpm-alpine
# Working directory
WORKDIR /var/www
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community shadow
# Usuario para Laravel
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www
RUN apk del --no-cache shadow
# Cambiar usuario actual a www
USER www
# Exponer puerto 9000 y levantar fpm server
EXPOSE 9000
CMD ["php-fpm"]

